<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ContentMapConverterWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/ContentMapConverterWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/ContentMapConverterWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://utils/">
    <import location="http://localhost:5050/TransferClient/ContentMapConverter?wsdl" namespace="http://utils/"/>
    <plnk:partnerLinkType name="ContentMapConverterLinkType">
        <plnk:role name="ContentMapConverterRole" portType="ns:ContentMapConverter"/>
    </plnk:partnerLinkType>
</definitions>
