<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="RTWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/RTWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/RTWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://rt/">
    <import location="http://localhost:5050/TransferClient/RT?wsdl" namespace="http://rt/"/>
    <plnk:partnerLinkType name="RTLinkType">
        <plnk:role name="RTRole" portType="ns:RT"/>
    </plnk:partnerLinkType>
</definitions>
