<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="FootPrints11Wrapper" targetNamespace="http://enterprise.netbeans.org/bpel/FootPrints11Wrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/FootPrints11Wrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://fp/">
    <import location="http://localhost:8080/TransferClient/FootPrints11?WSDL" namespace="http://fp/"/>
    <plnk:partnerLinkType name="FootPrints11LinkType">
        <plnk:role name="FootPrints11Role" portType="ns:FootPrints11"/>
    </plnk:partnerLinkType>
</definitions>
