name: PR Build
on: pull_request
jobs:
  code-quality:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      # Don't fail all elements of the matrix if one fails
      fail-fast: false
      matrix:
        node-version: ['22.x', '24.x']
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies in ws/rest-client
        run: npm ci
        working-directory: src/java/ws/rest-client
      - name: Build in ws/rest-client
        run: npm run build
        working-directory: src/java/ws/rest-client
      - name: Lint in ws/rest-client
        run: npm run lint
        working-directory: src/java/ws/rest-client
